### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by marosmola** [woocommerce/wc-api-python#40]
Sometimes when when i want to get response in json format:
`r.json()`

i get this error:
`json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)`

what could be the problem? is there any way to fix this?

**Comment by claudiosanches** [comment]
> what could be the problem? is there any way to fix this?

The problem is already in the error message: `Unexpected UTF-8 BOM (decode using utf-8-sig)`.

For some reason your website is inserting a BOM character in all WordPress REST API responses, generally this comes from your `wp-config.php` file, people open in Windows notepad and introduces BOM character, so just try to find where it comes and remove, but not an issue with this library.
